// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBji7ELJ7InPZToXLXG1i01qLKTk8O_vJo',
    appId: '1:210711427505:web:fb865de8e5a63cb322e590',
    messagingSenderId: '210711427505',
    projectId: 'abu-fasion-store',
    authDomain: 'abu-fasion-store.firebaseapp.com',
    storageBucket: 'abu-fasion-store.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdK7xRnJPuTX7_Fvc2zI5JesCpf-9INt4',
    appId: '1:210711427505:android:7e3133ad0fcc2cf222e590',
    messagingSenderId: '210711427505',
    projectId: 'abu-fasion-store',
    storageBucket: 'abu-fasion-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9xHFgmY0nMSnypIxu6bdmInSfmEZ8c28',
    appId: '1:210711427505:ios:4a8524d85226cd0722e590',
    messagingSenderId: '210711427505',
    projectId: 'abu-fasion-store',
    storageBucket: 'abu-fasion-store.firebasestorage.app',
    iosBundleId: 'com.abufashion.abuFashionStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9xHFgmY0nMSnypIxu6bdmInSfmEZ8c28',
    appId: '1:210711427505:ios:4a8524d85226cd0722e590',
    messagingSenderId: '210711427505',
    projectId: 'abu-fasion-store',
    storageBucket: 'abu-fasion-store.firebasestorage.app',
    iosBundleId: 'com.abufashion.abuFashionStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBji7ELJ7InPZToXLXG1i01qLKTk8O_vJo',
    appId: '1:210711427505:web:e7af941c8f7e9f1f22e590',
    messagingSenderId: '210711427505',
    projectId: 'abu-fasion-store',
    authDomain: 'abu-fasion-store.firebaseapp.com',
    storageBucket: 'abu-fasion-store.firebasestorage.app',
  );
}
